default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("DATABASE_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DATABASE_HOST") { 'localhost' } %>
  port:  <%= ENV.fetch("DATABASE_PORT") { 5432 } %>
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
#  sslmode: <%#= ENV.fetch("DATABASE_SSLMODE") { '' } %>
#  sslrootcert: <%#= ENV.fetch("DATABASE_SSLROOTCERT") { '' } %>

development:
  <<: *default

test:
  <<: *default
  database: project_desafio_test

production:
  <<: *default
